repos:
  -   repo: https://github.com/ambv/black
      rev: stable
      hooks:
        - id: black
          language_version: python3.8
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
        - id: check-yaml
        - id: end-of-file-fixer
        - id: trailing-whitespace
        - id: flake8
